# ArchipelagoOptions
#
# Created by The BUG Mod.

[ProfileSettings]

# XML key TXT_KEY_BUG_OPT_ARCHIPELAGO__ARCHIPELAGOSERVER_HOVER not found
# Default: archipelago.gg

Archipelago__ArchipelagoServer = archipelago.gg:35647

# XML key TXT_KEY_BUG_OPT_ARCHIPELAGO__ARCHIPELAGOUSERNAME_HOVER not found
# Default: Player1

Archipelago__ArchipelagoUsername = CivIVTest

# XML key TXT_KEY_BUG_OPT_ARCHIPELAGO__ARCHIPELAGOPASSWORD_HOVER not found
# Default: None

Archipelago__ArchipelagoPassword = ""

# XML key TXT_KEY_BUG_OPT_ARCHIPELAGO__ARCHIPELAGOCOMMAND_HOVER not found
# Default: None

Archipelago__ArchipelagoCommand = ""
Archipelago__ShowAnnouncements = True

# XML key TXT_KEY_BUG_OPT_ARCHIPELAGO__ARCHIPELAGOCOMMAND_HOVER not found
# Default: None